"""remove guardians, add username, link profiles

Revision ID: 1c5bb14f9ae4
Revises: fa06b4e695d5
Create Date: 2026-09-12 06:03:21.333281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1c5bb14f9ae4'
down_revision: Union[str, None] = 'fa06b4e695d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: order matters — drop the link table before the table it references.
    op.drop_table('student_guardian')
    op.drop_table('guardian_profiles')
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

    # Backfill usernames from the email local-part (unique-ified on clash).
    op.execute(sa.text("""
        UPDATE users u SET username = sub.username FROM (
            SELECT id, local ||
                CASE WHEN ROW_NUMBER() OVER (PARTITION BY local ORDER BY id) = 1
                     THEN '' ELSE (ROW_NUMBER() OVER (PARTITION BY local ORDER BY id))::text END
                AS username
            FROM (SELECT id, lower(split_part(email, '@', 1)) AS local FROM users WHERE username IS NULL) t
        ) sub WHERE u.id = sub.id
    """))
    # Link existing teacher/student profiles to logins sharing the same email.
    op.execute(sa.text("""
        UPDATE teacher_profiles tp SET user_id = u.id
        FROM users u WHERE tp.user_id IS NULL AND tp.email IS NOT NULL
          AND lower(tp.email) = lower(u.email) AND u.role = 'TEACHER'
    """))
    op.execute(sa.text("""
        UPDATE student_profiles sp SET user_id = u.id
        FROM users u WHERE sp.user_id IS NULL AND sp.email IS NOT NULL
          AND lower(sp.email) = lower(u.email) AND u.role = 'STUDENT'
    """))
    # Remove guardian logins: the GUARDIAN role no longer exists in the app.
    # (The 'userrole' DB enum keeps its old value; it is simply never used again.)
    op.execute(sa.text("DELETE FROM refresh_tokens WHERE user_id IN (SELECT id FROM users WHERE role = 'GUARDIAN')"))
    op.execute(sa.text("DELETE FROM users WHERE role = 'GUARDIAN'"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # NOTE: reverse of upgrade — recreate referenced table before the link table.
    op.create_table('guardian_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('guardian_profiles_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('guardian_profiles_pkey')),
    sa.UniqueConstraint('email', name=op.f('guardian_profiles_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('guardian_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student_guardian',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guardian_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian_profiles.id'], name=op.f('student_guardian_guardian_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('student_guardian_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'guardian_id', name=op.f('student_guardian_pkey'))
    )
    # ### end Alembic commands ###
