"""student division and guardian contact fields

Revision ID: ed2a1854a423
Revises: 1c5bb14f9ae4
Create Date: 2026-09-12 06:36:59.206637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed2a1854a423'
down_revision: Union[str, None] = '1c5bb14f9ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('division', sa.String(length=32), nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_name', sa.String(length=200), nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'guardian_phone')
    op.drop_column('student_profiles', 'guardian_name')
    op.drop_column('student_profiles', 'division')
    # ### end Alembic commands ###
