import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../../lib/api";

interface Exam { id: number; name: string; exam_type: string; class_id: number; }
interface DropdownItem { id: number; name: string; }
interface ExamRoutine {
  id: number; exam_id: number; exam_name: string; exam_type: string;
  class_id: number; class_name: string; section_id: number | null; section_name: string | null;
  subject_id: number; subject_name: string; teacher_id: number | null; teacher_name: string | null;
  group: string | null;
  exam_date: string; start_time: string; end_time: string; room: string | null;
}
interface AutoGeneratedItem {
  subject_id: number; subject_name: string; exam_date: string;
  start_time: string; end_time: string; room: string | null;
  teacher_id: number | null; teacher_name: string | null;
  slot: number; day: number; group: string | null;
}

const TIME_SLOTS = [
  { slot: 1, start: "09:00", end: "09:45", label: "Slot 1" },
  { slot: 2, start: "10:00", end: "10:45", label: "Slot 2" },
  { slot: 3, start: "11:00", end: "11:45", label: "Slot 3" },
  { slot: 4, start: "12:00", end: "12:45", label: "Slot 4" },
  { slot: 5, start: "13:00", end: "13:45", label: "Slot 5" },
  { slot: 6, start: "14:00", end: "14:45", label: "Slot 6" },
];

const SUBJECT_COLORS = [
  "from-blue-500 to-blue-600", "from-emerald-500 to-emerald-600", "from-violet-500 to-violet-600",
  "from-amber-500 to-amber-600", "from-rose-500 to-rose-600", "from-cyan-500 to-cyan-600",
  "from-pink-500 to-pink-600", "from-teal-500 to-teal-600", "from-orange-500 to-orange-600",
  "from-indigo-500 to-indigo-600", "from-lime-500 to-lime-600", "from-fuchsia-500 to-fuchsia-600",
];

function getSubjectColor(subjectId: number): string {
  return SUBJECT_COLORS[subjectId % SUBJECT_COLORS.length];
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
}

function formatDateShort(iso: string): string {
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function getDayName(iso: string): string {
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString("en-US", { weekday: "long" });
}

function getSlotIndex(time: string): number {
  return TIME_SLOTS.findIndex(s => s.start <= time && s.end >= time);
}

export function AdminExamRoutinePage() {
  const queryClient = useQueryClient();
  const [selectedExam, setSelectedExam] = useState("");
  const [selectedClass, setSelectedClass] = useState("");
  const [selectedGroup, setSelectedGroup] = useState("");
  const [startDate, setStartDate] = useState("");
  const [preview, setPreview] = useState<AutoGeneratedItem[] | null>(null);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editForm, setEditForm] = useState({ exam_date: "", start_time: "", end_time: "", room: "", teacher_id: "" });

  const GROUPS = [
    { value: "SCIENCE", label: "Science Group" },
    { value: "HUMANITIES", label: "Humanities / Arts Group" },
    { value: "BUSINESS_STUDIES", label: "Commerce / Business Group" },
  ];

  const { data: exams } = useQuery({
    queryKey: ["admin-exams"],
    queryFn: async () => (await api.get("/exams")).data as Exam[],
  });

  const { data: classes } = useQuery({
    queryKey: ["admin-classes"],
    queryFn: async () => (await api.get("/admin/classes")).data as DropdownItem[],
  });

  const { data: existingRoutines } = useQuery({
    queryKey: ["exam-routines", selectedExam, selectedClass, selectedGroup],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (selectedExam) params.set("exam_id", selectedExam);
      if (selectedClass) params.set("class_id", selectedClass);
      if (selectedGroup) params.set("group", selectedGroup);
      return (await api.get(`/exams/routines?${params}`)).data as ExamRoutine[];
    },
    enabled: !!selectedExam,
  });

  const previewMutation = useMutation({
    mutationFn: async () => {
      const params = new URLSearchParams({ exam_id: selectedExam, class_id: selectedClass, start_date: startDate });
      if (selectedGroup) params.set("group", selectedGroup);
      return (await api.get(`/exams/routines/auto-generate?${params}`)).data as {
        items: AutoGeneratedItem[]; total_subjects: number; total_days: number;
        time_slots: { slot: number; start: string; end: string }[];
      };
    },
    onSuccess: (data) => setPreview(data.items),
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      const params = new URLSearchParams({ exam_id: selectedExam, class_id: selectedClass, start_date: startDate });
      if (selectedGroup) params.set("group", selectedGroup);
      return (await api.post(`/exams/routines/auto-generate?${params}`)).data;
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["exam-routines"] }); setPreview(null); },
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, data }: { id: number; data: Record<string, unknown> }) =>
      (await api.put(`/exams/routines/${id}`, data)).data,
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["exam-routines"] }); setEditingId(null); },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => api.delete(`/exams/routines/${id}`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["exam-routines"] }),
  });

  const selectedExamObj = exams?.find(e => e.id === Number(selectedExam));
  const selectedClassObj = classes?.find(c => c.id === Number(selectedClass));

  // Detect if class has groups (class 9, 10 etc.)
  const classNum = selectedClass ? parseInt(selectedClassObj?.name?.match(/\d+/)?.[0] || "0") : 0;
  const hasGroups = classNum >= 9;

  const startEdit = (r: ExamRoutine) => {
    setEditingId(r.id);
    setEditForm({ exam_date: r.exam_date, start_time: r.start_time, end_time: r.end_time, room: r.room || "", teacher_id: r.teacher_id?.toString() || "" });
  };

  const saveEdit = (id: number, subject_id: number) => {
    updateMutation.mutate({
      id, data: {
        exam_id: Number(selectedExam), class_id: Number(selectedClass), subject_id,
        exam_date: editForm.exam_date, start_time: editForm.start_time, end_time: editForm.end_time,
        room: editForm.room || null, teacher_id: editForm.teacher_id ? Number(editForm.teacher_id) : null,
      },
    });
  };

  // Build timetable grid data
  function buildGrid(routines: (ExamRoutine | AutoGeneratedItem)[]) {
    const dates = [...new Set(routines.map(r => r.exam_date))].sort();
    const grid: Record<string, Record<number, (ExamRoutine | AutoGeneratedItem)[]>> = {};
    for (const d of dates) grid[d] = {};
    for (const r of routines) {
      const slotIdx = getSlotIndex(r.start_time);
      if (slotIdx >= 0) {
        if (!grid[r.exam_date]) grid[r.exam_date] = {};
        if (!grid[r.exam_date][slotIdx]) grid[r.exam_date][slotIdx] = [];
        grid[r.exam_date][slotIdx].push(r);
      }
    }
    return { dates, grid };
  }

  const renderTimetable = (routines: (ExamRoutine | AutoGeneratedItem)[], isPreview: boolean) => {
    const { dates, grid } = buildGrid(routines);

    const dayColors = ["bg-indigo-500", "bg-emerald-500", "bg-amber-500"];

    return (
      <div className="flex gap-6 overflow-x-auto pb-2">
        {dates.map((dateStr, dayIdx) => (
          <div key={dateStr} className="min-w-[320px] flex-1">
            {/* Day Header */}
            <div className="flex items-center gap-3 mb-3">
              <div className={`w-1.5 h-8 rounded-full ${dayColors[dayIdx] || "bg-slate-400"}`} />
              <div>
                <p className="text-sm font-extrabold text-slate-900">Day {dayIdx + 1}</p>
                <p className="text-xs text-slate-500">{getDayName(dateStr)}, {formatDateShort(dateStr)}</p>
              </div>
              <span className="text-[10px] font-bold bg-slate-100 text-slate-600 px-2.5 py-1 rounded-full">
                {Object.values(grid[dateStr] || {}).filter(Boolean).length} exam(s)
              </span>
            </div>

            {/* Day Table */}
            <div className="overflow-x-auto rounded-xl border border-slate-200">
              <table className="w-full border-collapse">
                <thead>
                  <tr>
                    <th className="p-2.5 text-center text-[10px] font-bold text-slate-500 uppercase bg-slate-50 border-b border-slate-200 w-10">
                      #
                    </th>
                    <th className="p-2.5 text-center text-[10px] font-bold text-slate-500 uppercase bg-slate-50 border-b border-slate-200 w-20">
                      Time
                    </th>
                    <th className="p-2.5 text-left text-[10px] font-bold text-slate-500 uppercase bg-slate-50 border-b border-slate-200">
                      Subject
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {TIME_SLOTS.map((slot, slotIdx) => {
                    const items = grid[dateStr]?.[slotIdx] || [];
                    const item = items[0];

                    return (
                      <tr key={slot.slot} className="border-b border-slate-100 last:border-0">
                        {/* Slot Number */}
                        <td className="p-2 text-center bg-slate-50/50">
                          <span className="inline-flex items-center justify-center w-6 h-6 rounded-md bg-indigo-100 text-indigo-700 text-[10px] font-extrabold">
                            {slot.slot}
                          </span>
                        </td>

                        {/* Time */}
                        <td className="p-2 text-center">
                          <p className="text-[10px] font-bold text-slate-700">{slot.start}</p>
                          <p className="text-[8px] text-slate-400">to</p>
                          <p className="text-[10px] font-bold text-slate-700">{slot.end}</p>
                        </td>

                        {/* Subject Cell */}
                        <td className="p-1.5">
                          {!item ? (
                            <div className="h-[48px] rounded-lg bg-slate-50 border border-dashed border-slate-200 flex items-center justify-center">
                              <span className="text-[9px] text-slate-300 font-medium">Free</span>
                            </div>
                          ) : (() => {
                            const isExamRoutine = "id" in item && !isPreview;
                            const routineItem = item as ExamRoutine;

                            if (editingId && isExamRoutine && routineItem.id === editingId) {
                              return (
                                <div className="rounded-lg border-2 border-indigo-300 bg-indigo-50 p-1.5 space-y-1">
                                  <div className="flex gap-1">
                                    <input type="date" value={editForm.exam_date} onChange={(e) => setEditForm({ ...editForm, exam_date: e.target.value })}
                                      className="flex-1 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-indigo-500" />
                                    <input type="time" value={editForm.start_time} onChange={(e) => setEditForm({ ...editForm, start_time: e.target.value })}
                                      className="w-16 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-indigo-500" />
                                    <input type="time" value={editForm.end_time} onChange={(e) => setEditForm({ ...editForm, end_time: e.target.value })}
                                      className="w-16 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-indigo-500" />
                                  </div>
                                  <div className="flex gap-1">
                                    <input type="text" value={editForm.room} onChange={(e) => setEditForm({ ...editForm, room: e.target.value })}
                                      placeholder="Room" className="flex-1 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-indigo-500" />
                                    <button onClick={() => saveEdit(routineItem.id, routineItem.subject_id)} disabled={updateMutation.isPending}
                                      className="px-2 py-0.5 rounded bg-emerald-600 text-white text-[9px] font-bold hover:bg-emerald-700 disabled:opacity-50">Save</button>
                                    <button onClick={() => setEditingId(null)}
                                      className="px-2 py-0.5 rounded bg-slate-200 text-slate-600 text-[9px] font-bold hover:bg-slate-300">Cancel</button>
                                  </div>
                                </div>
                              );
                            }

                            const color = getSubjectColor(item.subject_id);
                            return (
                              <div className={`h-[48px] rounded-lg bg-gradient-to-br ${color} px-2.5 py-1.5 text-white shadow-sm hover:shadow-md transition-shadow group relative flex items-center justify-between`}>
                                <div className="min-w-0 flex-1">
                                  <p className="text-[10px] font-extrabold truncate">{item.subject_name}</p>
                                  <p className="text-[8px] opacity-80 truncate">
                                    {item.room ? `Room: ${item.room}` : ""}
                                    {item.teacher_name ? ` • ${item.teacher_name}` : ""}
                                  </p>
                                </div>
                                {isExamRoutine && (
                                  <div className="flex gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity shrink-0 ml-1">
                                    <button onClick={() => startEdit(routineItem)}
                                      className="p-0.5 rounded bg-white/25 hover:bg-white/40 backdrop-blur-sm transition" title="Edit">
                                      <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                      </svg>
                                    </button>
                                    <button onClick={() => { if (confirm("Delete this entry?")) deleteMutation.mutate(routineItem.id); }}
                                      className="p-0.5 rounded bg-white/25 hover:bg-red-500/80 backdrop-blur-sm transition" title="Delete">
                                      <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                                      </svg>
                                    </button>
                                  </div>
                                )}
                              </div>
                            );
                          })()}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        ))}
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-indigo-700 to-indigo-500 rounded-2xl p-6 text-white shadow">
        <h2 className="text-2xl font-extrabold">Exam Routine</h2>
        <p className="text-indigo-100 text-sm mt-1">45-min exams · 15-min gaps · 6 slots/day · up to 3 days</p>
      </div>

      {/* Step 1 */}
      <div className="bg-white rounded-2xl border border-slate-200 p-5">
        <h3 className="text-sm font-bold text-slate-700 mb-4">Step 1: Select Exam & Class</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-500 mb-1">Exam *</label>
            <select value={selectedExam} onChange={(e) => { setSelectedExam(e.target.value); setPreview(null); }}
              className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
              <option value="">-- Select Exam --</option>
              {exams?.map(e => <option key={e.id} value={e.id}>{e.name} ({e.exam_type.replace("_", " ")})</option>)}
            </select>
            {!exams || exams.length === 0 ? <p className="text-[10px] text-amber-600 mt-1">No exams found. Create an exam first.</p> : null}
          </div>
          <div>
            <label className="block text-xs font-semibold text-slate-500 mb-1">Class *</label>
            <select value={selectedClass} onChange={(e) => { setSelectedClass(e.target.value); setSelectedGroup(""); setPreview(null); }}
              className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
              <option value="">-- Select Class --</option>
              {classes?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
            </select>
          </div>
          {hasGroups && (
            <div>
              <label className="block text-xs font-semibold text-slate-500 mb-1">Group *</label>
              <select value={selectedGroup} onChange={(e) => { setSelectedGroup(e.target.value); setPreview(null); }}
                className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                <option value="">-- Select Group --</option>
                {GROUPS.map(g => <option key={g.value} value={g.value}>{g.label}</option>)}
              </select>
            </div>
          )}
        </div>
      </div>

      {/* Step 2: Generate */}
      {selectedExam && selectedClass && (!hasGroups || selectedGroup) && (
        <div className="bg-white rounded-2xl border border-slate-200 p-5">
          <h3 className="text-sm font-bold text-slate-700 mb-4">
            Step 2: Generate — {selectedExamObj?.name} · {selectedClassObj?.name}{selectedGroup ? ` · ${GROUPS.find(g => g.value === selectedGroup)?.label}` : ""}
          </h3>
          <div className="flex flex-col sm:flex-row gap-4 items-end mb-4">
            <div className="flex-1">
              <label className="block text-xs font-semibold text-slate-500 mb-1">Start Date *</label>
              <input type="date" value={startDate} onChange={(e) => { setStartDate(e.target.value); setPreview(null); }}
                className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
            <div className="flex gap-2">
              <button onClick={() => previewMutation.mutate()} disabled={!startDate || previewMutation.isPending}
                className="px-5 py-2.5 rounded-xl bg-slate-100 text-slate-700 text-sm font-semibold hover:bg-slate-200 disabled:opacity-50 transition">
                {previewMutation.isPending ? "Generating..." : "Preview"}
              </button>
              {preview && (
                <button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending}
                  className="px-5 py-2.5 rounded-xl bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-700 disabled:opacity-50 transition shadow-md shadow-indigo-200">
                  {saveMutation.isPending ? "Saving..." : `Save ${preview.length} Routine(s)`}
                </button>
              )}
            </div>
          </div>
          {previewMutation.isError && <p className="text-xs text-red-600">Failed. Check your inputs.</p>}

          {/* Preview Timetable */}
          {preview && preview.length > 0 && (
            <div className="mt-2">
              <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-3">
                Preview — {preview.length} subjects across {Math.ceil(preview.length / 6)} day(s)
              </p>
              {renderTimetable(preview, true)}
            </div>
          )}
        </div>
      )}

      {/* Existing Routines Timetable */}
      {selectedExam && (!hasGroups || selectedGroup) && existingRoutines && existingRoutines.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200 p-5">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-bold text-slate-700">
              Scheduled Exams ({existingRoutines.length} entries){selectedGroup ? ` — ${GROUPS.find(g => g.value === selectedGroup)?.label}` : ""}
            </h3>
            <p className="text-[10px] text-slate-400">Hover a card to edit or delete</p>
          </div>
          {renderTimetable(existingRoutines, false)}
        </div>
      )}

      {/* Empty State */}
      {selectedExam && selectedClass && (!hasGroups || selectedGroup) && existingRoutines && existingRoutines.length === 0 && !preview && (
        <div className="bg-white rounded-2xl border border-slate-200 p-8 text-center">
          <div className="w-16 h-16 rounded-2xl bg-indigo-50 flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
          <p className="text-sm font-semibold text-slate-900">No routines scheduled yet</p>
          <p className="text-xs text-slate-500 mt-1">Pick a start date and click Preview to auto-generate</p>
        </div>
      )}
    </div>
  );
}
