import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../../lib/api";

interface Exam { id: number; name: string; exam_type: string; class_id: number; }
interface DropdownItem { id: number; name: string; }
interface ExamRoutine {
  id: number; exam_id: number; exam_name: string; exam_type: string;
  class_id: number; class_name: string; section_id: number | null; section_name: string | null;
  subject_id: number; subject_name: string; teacher_id: number | null; teacher_name: string | null;
  group: string | null;
  exam_date: string; start_time: string; end_time: string; room: string | null;
}
interface AutoGeneratedItem {
  subject_id: number; subject_name: string; exam_date: string;
  start_time: string; end_time: string; room: string | null;
  teacher_id: number | null; teacher_name: string | null;
  slot: number; day: number; group: string | null;
}

const MONTHLY_SLOTS = [
  { slot: 1, start: "09:00", end: "09:45", label: "Slot 1" },
  { slot: 2, start: "10:00", end: "10:45", label: "Slot 2" },
  { slot: 3, start: "11:00", end: "11:45", label: "Slot 3" },
  { slot: 4, start: "12:00", end: "12:45", label: "Slot 4" },
  { slot: 5, start: "13:00", end: "13:45", label: "Slot 5" },
  { slot: 6, start: "14:00", end: "14:45", label: "Slot 6" },
];

const HALFYEARLY_SLOTS = [
  { slot: 1, start: "09:00", end: "12:00", label: "Session 1 (9 AM - 12 PM)" },
  { slot: 2, start: "13:00", end: "16:00", label: "Session 2 (1 PM - 4 PM)" },
];

const SUBJECT_COLORS = [
  "from-blue-500 to-blue-600", "from-emerald-500 to-emerald-600", "from-violet-500 to-violet-600",
  "from-amber-500 to-amber-600", "from-rose-500 to-rose-600", "from-cyan-500 to-cyan-600",
  "from-pink-500 to-pink-600", "from-teal-500 to-teal-600", "from-orange-500 to-orange-600",
  "from-indigo-500 to-indigo-600", "from-lime-500 to-lime-600", "from-fuchsia-500 to-fuchsia-600",
];

const DAY_COLORS = [
  "bg-indigo-500", "bg-emerald-500", "bg-amber-500", "bg-rose-500", "bg-cyan-500",
  "bg-violet-500", "bg-pink-500", "bg-teal-500", "bg-orange-500", "bg-blue-500",
  "bg-lime-500", "bg-fuchsia-500", "bg-red-500", "bg-yellow-500", "bg-purple-500",
];

function getSubjectColor(subjectId: number): string {
  return SUBJECT_COLORS[subjectId % SUBJECT_COLORS.length];
}

function formatDateShort(iso: string): string {
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function getDayName(iso: string): string {
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString("en-US", { weekday: "long" });
}

function isMonthlyExam(examType: string): boolean {
  return examType === "CLASS_TEST" || examType === "MONTHLY_TEST";
}

function getSlotsForExamType(examType: string) {
  return isMonthlyExam(examType) ? MONTHLY_SLOTS : HALFYEARLY_SLOTS;
}

export function AdminExamRoutinePage() {
  const queryClient = useQueryClient();
  const [selectedExam, setSelectedExam] = useState("");
  const [selectedClass, setSelectedClass] = useState("");
  const [selectedGroup, setSelectedGroup] = useState("");
  const [startDate, setStartDate] = useState("");
  const [preview, setPreview] = useState<AutoGeneratedItem[] | null>(null);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editForm, setEditForm] = useState({ exam_date: "", start_time: "", end_time: "", room: "", teacher_id: "" });
  const [showAddForm, setShowAddForm] = useState(false);
  const [addForm, setAddForm] = useState({ subject_id: "", exam_date: "", start_time: "", end_time: "", room: "", teacher_id: "" });

  const GROUPS = [
    { value: "SCIENCE", label: "Science Group" },
    { value: "HUMANITIES", label: "Humanities / Arts Group" },
    { value: "BUSINESS_STUDIES", label: "Commerce / Business Group" },
  ];

  const { data: exams } = useQuery({
    queryKey: ["admin-exams"],
    queryFn: async () => (await api.get("/exams")).data as Exam[],
  });

  const { data: classes } = useQuery({
    queryKey: ["admin-classes"],
    queryFn: async () => (await api.get("/admin/classes")).data as DropdownItem[],
  });

  const { data: subjects } = useQuery({
    queryKey: ["admin-subjects"],
    queryFn: async () => (await api.get("/admin/subjects")).data as DropdownItem[],
  });

  const { data: teachers } = useQuery({
    queryKey: ["admin-teachers"],
    queryFn: async () => {
      const d = (await api.get("/admin/teachers")).data as { id: number; first_name: string; last_name: string }[];
      return d.map(t => ({ id: t.id, name: `${t.first_name} ${t.last_name}` }));
    },
  });

  const { data: existingRoutines } = useQuery({
    queryKey: ["exam-routines", selectedExam, selectedClass, selectedGroup],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (selectedExam) params.set("exam_id", selectedExam);
      if (selectedClass) params.set("class_id", selectedClass);
      if (selectedGroup) params.set("group", selectedGroup);
      return (await api.get(`/exams/routines?${params}`)).data as ExamRoutine[];
    },
    enabled: !!selectedExam,
  });

  const previewMutation = useMutation({
    mutationFn: async () => {
      const params = new URLSearchParams({ exam_id: selectedExam, class_id: selectedClass, start_date: startDate });
      if (selectedGroup) params.set("group", selectedGroup);
      return (await api.get(`/exams/routines/auto-generate?${params}`)).data as {
        items: AutoGeneratedItem[]; total_subjects: number; total_days: number;
        exam_type: string; slots_per_day: number; max_days: number;
        time_slots: { slot: number; start: string; end: string }[];
      };
    },
    onSuccess: (data) => setPreview(data.items),
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      const params = new URLSearchParams({ exam_id: selectedExam, class_id: selectedClass, start_date: startDate });
      if (selectedGroup) params.set("group", selectedGroup);
      return (await api.post(`/exams/routines/auto-generate?${params}`)).data;
    },
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["exam-routines"] }); setPreview(null); },
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, data }: { id: number; data: Record<string, unknown> }) =>
      (await api.put(`/exams/routines/${id}`, data)).data,
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["exam-routines"] }); setEditingId(null); },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => api.delete(`/exams/routines/${id}`),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["exam-routines"] }),
  });

  const addMutation = useMutation({
    mutationFn: async (data: Record<string, unknown>) => (await api.post("/exams/routines", data)).data,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["exam-routines"] });
      setShowAddForm(false);
      setAddForm({ subject_id: "", exam_date: "", start_time: "", end_time: "", room: "", teacher_id: "" });
    },
  });

  const selectedExamObj = exams?.find(e => e.id === Number(selectedExam));
  const selectedClassObj = classes?.find(c => c.id === Number(selectedClass));

  const classNum = selectedClass ? parseInt(selectedClassObj?.name?.match(/\d+/)?.[0] || "0") : 0;
  const hasGroups = classNum >= 9;
  const examType = selectedExamObj?.exam_type || "MONTHLY_TEST";
  const isMonthly = isMonthlyExam(examType);
  const timeSlots = getSlotsForExamType(examType);

  const startEdit = (r: ExamRoutine) => {
    setEditingId(r.id);
    setEditForm({ exam_date: r.exam_date, start_time: r.start_time, end_time: r.end_time, room: r.room || "", teacher_id: r.teacher_id?.toString() || "" });
  };

  const saveEdit = (id: number, subject_id: number) => {
    updateMutation.mutate({
      id, data: {
        exam_id: Number(selectedExam), class_id: Number(selectedClass), subject_id,
        exam_date: editForm.exam_date, start_time: editForm.start_time, end_time: editForm.end_time,
        room: editForm.room || null, teacher_id: editForm.teacher_id ? Number(editForm.teacher_id) : null,
      },
    });
  };

  const handleAddSubject = () => {
    if (!addForm.subject_id || !addForm.exam_date || !addForm.start_time || !addForm.end_time) return;
    addMutation.mutate({
      exam_id: Number(selectedExam),
      class_id: Number(selectedClass),
      subject_id: Number(addForm.subject_id),
      group: selectedGroup || null,
      exam_date: addForm.exam_date,
      start_time: addForm.start_time,
      end_time: addForm.end_time,
      room: addForm.room || null,
      teacher_id: addForm.teacher_id ? Number(addForm.teacher_id) : null,
    });
  };

  // Get available dates from existing routines
  const availableDates = existingRoutines
    ? [...new Set(existingRoutines.map(r => r.exam_date))].sort()
    : [];

  function buildGrid(routines: (ExamRoutine | AutoGeneratedItem)[]) {
    const dates = [...new Set(routines.map(r => r.exam_date))].sort();
    const grid: Record<string, Record<number, (ExamRoutine | AutoGeneratedItem)[]>> = {};
    for (const d of dates) grid[d] = {};
    for (const r of routines) {
      const slotIdx = timeSlots.findIndex(s => s.start <= r.start_time && s.end >= r.end_time);
      if (slotIdx >= 0) {
        if (!grid[r.exam_date]) grid[r.exam_date] = {};
        if (!grid[r.exam_date][slotIdx]) grid[r.exam_date][slotIdx] = [];
        grid[r.exam_date][slotIdx].push(r);
      }
    }
    return { dates, grid };
  }

  const renderTimetable = (routines: (ExamRoutine | AutoGeneratedItem)[], isPreview: boolean) => {
    const { dates, grid } = buildGrid(routines);

    return (
      <div className="flex gap-6 overflow-x-auto pb-2">
        {dates.map((dateStr, dayIdx) => (
          <div key={dateStr} className="min-w-[320px] flex-1">
            {/* Day Header */}
            <div className="flex items-center gap-3 mb-3">
              <div className={`w-1.5 h-8 rounded-full ${DAY_COLORS[dayIdx % DAY_COLORS.length]}`} />
              <div>
                <p className="text-sm font-extrabold text-slate-900">Day {dayIdx + 1}</p>
                <p className="text-xs text-slate-500">{getDayName(dateStr)}, {formatDateShort(dateStr)}</p>
              </div>
              <span className="text-[10px] font-bold bg-slate-100 text-slate-600 px-2.5 py-1 rounded-full">
                {Object.values(grid[dateStr] || {}).filter(Boolean).length} exam(s)
              </span>
            </div>

            {/* Day Table */}
            <div className="overflow-x-auto rounded-xl border border-slate-200">
              <table className="w-full border-collapse">
                <thead>
                  <tr>
                    <th className="p-2.5 text-center text-[10px] font-bold text-slate-500 uppercase bg-slate-50 border-b border-slate-200 w-10">#</th>
                    <th className="p-2.5 text-center text-[10px] font-bold text-slate-500 uppercase bg-slate-50 border-b border-slate-200 w-28">Time</th>
                    <th className="p-2.5 text-left text-[10px] font-bold text-slate-500 uppercase bg-slate-50 border-b border-slate-200">Subject</th>
                  </tr>
                </thead>
                <tbody>
                  {timeSlots.map((slot, slotIdx) => {
                    const items = grid[dateStr]?.[slotIdx] || [];
                    const item = items[0];

                    return (
                      <tr key={slot.slot} className="border-b border-slate-100 last:border-0">
                        <td className="p-2 text-center bg-slate-50/50">
                          <span className="inline-flex items-center justify-center w-6 h-6 rounded-md bg-purple-100 text-purple-700 text-[10px] font-extrabold">
                            {slot.slot}
                          </span>
                        </td>
                        <td className="p-2 text-center">
                          <p className="text-[10px] font-bold text-slate-700">{slot.start}</p>
                          <p className="text-[8px] text-slate-400">to</p>
                          <p className="text-[10px] font-bold text-slate-700">{slot.end}</p>
                        </td>
                        <td className="p-1.5">
                          {!item ? (
                            <div className="h-[48px] rounded-lg bg-slate-50 border border-dashed border-slate-200 flex items-center justify-center">
                              <span className="text-[9px] text-slate-300 font-medium">Free</span>
                            </div>
                          ) : (() => {
                            const isExamRoutine = "id" in item && !isPreview;
                            const routineItem = item as ExamRoutine;

                            if (editingId && isExamRoutine && routineItem.id === editingId) {
                              return (
                                <div className="rounded-lg border-2 border-purple-300 bg-purple-50 p-1.5 space-y-1">
                                  <div className="flex gap-1">
                                    <input type="date" value={editForm.exam_date} onChange={(e) => setEditForm({ ...editForm, exam_date: e.target.value })}
                                      className="flex-1 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-purple-500" />
                                    <input type="time" value={editForm.start_time} onChange={(e) => setEditForm({ ...editForm, start_time: e.target.value })}
                                      className="w-16 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-purple-500" />
                                    <input type="time" value={editForm.end_time} onChange={(e) => setEditForm({ ...editForm, end_time: e.target.value })}
                                      className="w-16 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-purple-500" />
                                  </div>
                                  <div className="flex gap-1">
                                    <input type="text" value={editForm.room} onChange={(e) => setEditForm({ ...editForm, room: e.target.value })}
                                      placeholder="Room" className="flex-1 rounded border border-slate-300 px-1 py-0.5 text-[9px] focus:outline-none focus:ring-1 focus:ring-purple-500" />
                                    <button onClick={() => saveEdit(routineItem.id, routineItem.subject_id)} disabled={updateMutation.isPending}
                                      className="px-2 py-0.5 rounded bg-emerald-600 text-white text-[9px] font-bold hover:bg-emerald-700 disabled:opacity-50">Save</button>
                                    <button onClick={() => setEditingId(null)}
                                      className="px-2 py-0.5 rounded bg-slate-200 text-slate-600 text-[9px] font-bold hover:bg-slate-300">Cancel</button>
                                  </div>
                                </div>
                              );
                            }

                            const color = getSubjectColor(item.subject_id);
                            return (
                              <div className={`h-[48px] rounded-lg bg-gradient-to-br ${color} px-2.5 py-1.5 text-white shadow-sm hover:shadow-md transition-shadow group relative flex items-center justify-between`}>
                                <div className="min-w-0 flex-1">
                                  <p className="text-[10px] font-extrabold truncate">{item.subject_name}</p>
                                  <p className="text-[8px] opacity-80 truncate">
                                    {item.room ? `Room: ${item.room}` : ""}
                                    {item.teacher_name ? ` • ${item.teacher_name}` : ""}
                                  </p>
                                </div>
                                {isExamRoutine && (
                                  <div className="flex gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity shrink-0 ml-1">
                                    <button onClick={() => startEdit(routineItem)}
                                      className="p-0.5 rounded bg-white/25 hover:bg-white/40 backdrop-blur-sm transition" title="Edit">
                                      <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                      </svg>
                                    </button>
                                    <button onClick={() => { if (confirm("Delete this entry?")) deleteMutation.mutate(routineItem.id); }}
                                      className="p-0.5 rounded bg-white/25 hover:bg-red-500/80 backdrop-blur-sm transition" title="Delete">
                                      <svg className="w-2.5 h-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                                      </svg>
                                    </button>
                                  </div>
                                )}
                              </div>
                            );
                          })()}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        ))}
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-violet-700 via-purple-600 to-indigo-600 rounded-2xl p-6 text-white shadow-lg shadow-purple-200">
        <div className="flex items-center gap-4">
          <div className="w-14 h-14 rounded-2xl bg-white/20 backdrop-blur-sm flex items-center justify-center">
            <svg className="w-7 h-7 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
          <div>
            <h1 className="text-2xl font-extrabold">Exam Routine</h1>
            <p className="text-purple-100 text-sm mt-0.5">
              Monthly: 45-min exams, 6/day, up to 3 days · Half-yearly/Final: 3-hour exams, 2/day, up to 15 days
            </p>
          </div>
        </div>
      </div>

      {/* Step 1 */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="flex items-center gap-3 px-6 py-4 border-b border-slate-100 bg-purple-50/50">
          <div className="w-9 h-9 rounded-xl bg-purple-100 flex items-center justify-center">
            <span className="text-sm font-extrabold text-purple-600">1</span>
          </div>
          <div>
            <h2 className="text-sm font-bold text-slate-900">Select Exam & Class</h2>
            <p className="text-xs text-slate-500">Choose the exam and class to generate routine</p>
          </div>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1.5">Exam *</label>
              <select value={selectedExam} onChange={(e) => { setSelectedExam(e.target.value); setPreview(null); }}
                className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition">
                <option value="">-- Select Exam --</option>
                {exams?.map(e => <option key={e.id} value={e.id}>{e.name} ({e.exam_type.replace("_", " ")})</option>)}
              </select>
              {!exams || exams.length === 0 ? <p className="text-[10px] text-amber-600 mt-1.5">No exams found. Create an exam first.</p> : null}
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-600 mb-1.5">Class *</label>
              <select value={selectedClass} onChange={(e) => { setSelectedClass(e.target.value); setSelectedGroup(""); setPreview(null); }}
                className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition">
                <option value="">-- Select Class --</option>
                {classes?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
            </div>
            {hasGroups && (
              <div>
                <label className="block text-xs font-semibold text-slate-600 mb-1.5">Group *</label>
                <select value={selectedGroup} onChange={(e) => { setSelectedGroup(e.target.value); setPreview(null); }}
                  className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition">
                  <option value="">-- Select Group --</option>
                  {GROUPS.map(g => <option key={g.value} value={g.value}>{g.label}</option>)}
                </select>
              </div>
            )}
          </div>
          {selectedExamObj && (
            <div className="mt-4 flex items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-50 border border-purple-200">
              <svg className="w-4 h-4 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <p className="text-xs font-semibold text-purple-700">
                {isMonthly
                  ? "Monthly Test: 45-min exams, 6 per day, up to 3 days (max 18 subjects)"
                  : "Half-yearly/Final: 3-hour exams, 2 per day (9-12, 13-16), up to 15 days (max 30 subjects)"}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Step 2: Generate */}
      {selectedExam && selectedClass && (!hasGroups || selectedGroup) && (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="flex items-center gap-3 px-6 py-4 border-b border-slate-100 bg-purple-50/50">
            <div className="w-9 h-9 rounded-xl bg-purple-100 flex items-center justify-center">
              <span className="text-sm font-extrabold text-purple-600">2</span>
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-900">Generate Routine</h2>
              <p className="text-xs text-slate-500">{selectedExamObj?.name} · {selectedClassObj?.name}{selectedGroup ? ` · ${GROUPS.find(g => g.value === selectedGroup)?.label}` : ""}</p>
            </div>
          </div>
          <div className="p-6">
            <div className="flex flex-col sm:flex-row gap-4 items-end mb-4">
              <div className="flex-1 max-w-xs">
                <label className="block text-xs font-semibold text-slate-600 mb-1.5">Start Date *</label>
                <input type="date" value={startDate} onChange={(e) => { setStartDate(e.target.value); setPreview(null); }}
                  className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition" />
              </div>
              <div className="flex gap-2">
                <button onClick={() => previewMutation.mutate()} disabled={!startDate || previewMutation.isPending}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-100 text-slate-700 text-sm font-semibold hover:bg-slate-200 disabled:opacity-50 transition">
                  {previewMutation.isPending ? (
                    <>
                      <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
                      Generating...
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                      </svg>
                      Preview
                    </>
                  )}
                </button>
                {preview && (
                  <button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending}
                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-purple-600 text-white text-sm font-semibold hover:bg-purple-700 disabled:opacity-50 transition shadow-md shadow-purple-200">
                    {saveMutation.isPending ? "Saving..." : `Save ${preview.length} Routine(s)`}
                  </button>
                )}
              </div>
            </div>
            {previewMutation.isError && <p className="text-xs text-red-600">Failed. Check your inputs.</p>}

            {/* Preview Timetable */}
            {preview && preview.length > 0 && (
              <div className="mt-2">
                <div className="flex items-center gap-2 mb-3">
                  <span className="inline-flex items-center px-2.5 py-1 rounded-full text-[10px] font-bold bg-purple-100 text-purple-700 border border-purple-200">
                    PREVIEW
                  </span>
                  <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">
                    {preview.length} subjects across {Math.ceil(preview.length / (isMonthly ? 6 : 2))} day(s)
                  </p>
                </div>
                {renderTimetable(preview, true)}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Existing Routines Timetable + Add Subject */}
      {selectedExam && (!hasGroups || selectedGroup) && existingRoutines && existingRoutines.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-50/50">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-purple-100 flex items-center justify-center">
                <svg className="w-5 h-5 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                </svg>
              </div>
              <div>
                <h2 className="text-sm font-bold text-slate-900">Scheduled Exams ({existingRoutines.length} entries){selectedGroup ? ` — ${GROUPS.find(g => g.value === selectedGroup)?.label}` : ""}</h2>
                <p className="text-xs text-slate-500">Hover a card to edit or delete</p>
              </div>
            </div>
            <button onClick={() => setShowAddForm(!showAddForm)}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-purple-600 text-white text-sm font-semibold hover:bg-purple-700 transition shadow-sm shadow-purple-200">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
              </svg>
              {showAddForm ? "Close" : "Add Subject in Routine"}
            </button>
          </div>

          {/* Add Subject Form */}
          {showAddForm && (
            <div className="px-6 py-4 border-b border-slate-100 bg-purple-50/50">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-7 h-7 rounded-lg bg-purple-100 flex items-center justify-center">
                  <svg className="w-4 h-4 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
                  </svg>
                </div>
                <p className="text-sm font-bold text-slate-700">Add Subject to Routine</p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 items-end">
                <div>
                  <label className="block text-xs font-semibold text-slate-600 mb-1.5">Subject *</label>
                  <select value={addForm.subject_id} onChange={(e) => setAddForm({ ...addForm, subject_id: e.target.value })}
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition">
                    <option value="">Select subject...</option>
                    {subjects?.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-600 mb-1.5">Date *</label>
                  <select value={addForm.exam_date} onChange={(e) => setAddForm({ ...addForm, exam_date: e.target.value })}
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition">
                    <option value="">Select date...</option>
                    {availableDates.map(d => <option key={d} value={d}>{getDayName(d)}, {formatDateShort(d)}</option>)}
                    <option value="__new__">+ Add new date</option>
                  </select>
                </div>
                {addForm.exam_date === "__new__" && (
                  <div>
                    <label className="block text-xs font-semibold text-slate-600 mb-1.5">New Date *</label>
                    <input type="date" value={addForm.exam_date === "__new__" ? "" : addForm.exam_date}
                      onChange={(e) => setAddForm({ ...addForm, exam_date: e.target.value })}
                      className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition" />
                  </div>
                )}
                <div>
                  <label className="block text-xs font-semibold text-slate-600 mb-1.5">Time Slot *</label>
                  <select value={`${addForm.start_time}-${addForm.end_time}`} onChange={(e) => {
                    const [s, en] = e.target.value.split("-");
                    setAddForm({ ...addForm, start_time: s, end_time: en });
                  }}
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition">
                    <option value="">Select time slot...</option>
                    {timeSlots.map(s => <option key={s.slot} value={`${s.start}-${s.end}`}>{s.label}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-600 mb-1.5">Room</label>
                  <input type="text" value={addForm.room} onChange={(e) => setAddForm({ ...addForm, room: e.target.value })}
                    placeholder="e.g. Room 101"
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition" />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-600 mb-1.5">Teacher</label>
                  <select value={addForm.teacher_id} onChange={(e) => setAddForm({ ...addForm, teacher_id: e.target.value })}
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition">
                    <option value="">Select teacher...</option>
                    {teachers?.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
                  </select>
                </div>
              </div>
              <div className="flex justify-end mt-4 gap-3">
                <button onClick={() => setShowAddForm(false)}
                  className="px-4 py-2.5 rounded-xl border border-slate-300 text-sm font-semibold text-slate-600 hover:bg-slate-100 transition">
                  Cancel
                </button>
                <button onClick={handleAddSubject} disabled={!addForm.subject_id || !addForm.exam_date || !addForm.start_time || !addForm.end_time || addMutation.isPending}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-purple-600 text-white text-sm font-semibold hover:bg-purple-700 disabled:opacity-50 transition shadow-sm shadow-purple-200">
                  {addMutation.isPending ? (
                    <>
                      <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
                      Adding...
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
                      </svg>
                      Add Subject
                    </>
                  )}
                </button>
              </div>
              {addMutation.isSuccess && (
                <div className="mt-3 flex items-center gap-2 px-4 py-3 rounded-xl bg-emerald-50 border border-emerald-200">
                  <svg className="w-5 h-5 text-emerald-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <p className="text-sm font-medium text-emerald-700">Subject added to routine.</p>
                </div>
              )}
              {addMutation.isError && (
                <div className="mt-3 flex items-center gap-2 px-4 py-3 rounded-xl bg-red-50 border border-red-200">
                  <svg className="w-5 h-5 text-red-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <p className="text-sm font-medium text-red-700">Failed to add subject. It may already exist for this date.</p>
                </div>
              )}
            </div>
          )}

          <div className="p-6">
            {renderTimetable(existingRoutines, false)}
          </div>
        </div>
      )}

      {/* Empty State */}
      {selectedExam && selectedClass && (!hasGroups || selectedGroup) && existingRoutines && existingRoutines.length === 0 && !preview && (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-12 text-center">
          <div className="w-16 h-16 rounded-2xl bg-purple-50 flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </div>
          <p className="text-sm font-semibold text-slate-900 mb-1">No routines scheduled yet</p>
          <p className="text-xs text-slate-500">Pick a start date and click Preview to auto-generate</p>
        </div>
      )}
    </div>
  );
}
